const font = {
  "info": {
    "@face": "KenVector-Future",
    "@size": "72",
    "@bold": "0",
    "@italic": "0",
    "@charset": "",
    "@unicode": "1",
    "@stretchH": "100",
    "@smooth": "1",
    "@aa": "1",
    "@padding": "1,1,1,1",
    "@spacing": "1,1",
    "@outline": "0"
  },
  "common": {
    "@lineHeight": "72",
    "@base": "63",
    "@scaleW": "376",
    "@scaleH": "380",
    "@pages": "1",
    "@packed": "0",
    "@alphaChnl": "0",
    "@redChnl": "4",
    "@greenChnl": "4",
    "@blueChnl": "4"
  },
  "pages": {
    "page": {
      "@id": "0",
      "@file": "ssr.png"
    }
  },
  "chars": {
    "@count": "64",
    "char": [
      {
        "@id": "32",
        "@x": "0",
        "@y": "0",
        "@width": "0",
        "@height": "0",
        "@xoffset": "0",
        "@yoffset": "0",
        "@xadvance": "18",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "33",
        "@x": "51",
        "@y": "213",
        "@width": "14",
        "@height": "50",
        "@xoffset": "17",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "34",
        "@x": "15",
        "@y": "357",
        "@width": "32",
        "@height": "23",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "35",
        "@x": "273",
        "@y": "51",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "36",
        "@x": "270",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "37",
        "@x": "270",
        "@y": "288",
        "@width": "41",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "51",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "38",
        "@x": "270",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "39",
        "@x": "66",
        "@y": "357",
        "@width": "14",
        "@height": "23",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "40",
        "@x": "353",
        "@y": "51",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "41",
        "@x": "321",
        "@y": "102",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "42",
        "@x": "270",
        "@y": "339",
        "@width": "32",
        "@height": "32",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "43",
        "@x": "219",
        "@y": "306",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "44",
        "@x": "0",
        "@y": "357",
        "@width": "14",
        "@height": "23",
        "@xoffset": "-1",
        "@yoffset": "53",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "45",
        "@x": "165",
        "@y": "357",
        "@width": "50",
        "@height": "14",
        "@xoffset": "-1",
        "@yoffset": "35",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "46",
        "@x": "51",
        "@y": "366",
        "@width": "14",
        "@height": "14",
        "@xoffset": "-1",
        "@yoffset": "53",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "47",
        "@x": "321",
        "@y": "153",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "48",
        "@x": "0",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "49",
        "@x": "353",
        "@y": "0",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "50",
        "@x": "0",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "51",
        "@x": "0",
        "@y": "204",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "52",
        "@x": "0",
        "@y": "255",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "53",
        "@x": "0",
        "@y": "306",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "54",
        "@x": "69",
        "@y": "0",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "55",
        "@x": "69",
        "@y": "51",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "56",
        "@x": "66",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "57",
        "@x": "66",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "58",
        "@x": "51",
        "@y": "264",
        "@width": "14",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "59",
        "@x": "51",
        "@y": "102",
        "@width": "14",
        "@height": "59",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "61",
        "@x": "270",
        "@y": "204",
        "@width": "50",
        "@height": "32",
        "@xoffset": "-1",
        "@yoffset": "26",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "63",
        "@x": "219",
        "@y": "255",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "64",
        "@x": "273",
        "@y": "0",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "65",
        "@x": "66",
        "@y": "204",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "66",
        "@x": "66",
        "@y": "255",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "67",
        "@x": "66",
        "@y": "306",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "68",
        "@x": "120",
        "@y": "0",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "69",
        "@x": "120",
        "@y": "51",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "70",
        "@x": "117",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "71",
        "@x": "117",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "72",
        "@x": "117",
        "@y": "204",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "73",
        "@x": "51",
        "@y": "162",
        "@width": "14",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "74",
        "@x": "270",
        "@y": "237",
        "@width": "41",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "51",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "75",
        "@x": "117",
        "@y": "255",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "76",
        "@x": "117",
        "@y": "306",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "77",
        "@x": "0",
        "@y": "0",
        "@width": "68",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "78",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "78",
        "@x": "171",
        "@y": "0",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "79",
        "@x": "171",
        "@y": "51",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "80",
        "@x": "168",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "81",
        "@x": "168",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "82",
        "@x": "168",
        "@y": "204",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "83",
        "@x": "168",
        "@y": "255",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "84",
        "@x": "168",
        "@y": "306",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "85",
        "@x": "222",
        "@y": "0",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "86",
        "@x": "222",
        "@y": "51",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "87",
        "@x": "0",
        "@y": "51",
        "@width": "68",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "78",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "88",
        "@x": "219",
        "@y": "102",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "89",
        "@x": "219",
        "@y": "153",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "90",
        "@x": "219",
        "@y": "204",
        "@width": "50",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "91",
        "@x": "321",
        "@y": "204",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "93",
        "@x": "321",
        "@y": "255",
        "@width": "23",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "33",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "94",
        "@x": "81",
        "@y": "357",
        "@width": "32",
        "@height": "23",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "95",
        "@x": "114",
        "@y": "357",
        "@width": "50",
        "@height": "14",
        "@xoffset": "-1",
        "@yoffset": "53",
        "@xadvance": "60",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "123",
        "@x": "324",
        "@y": "0",
        "@width": "28",
        "@height": "50",
        "@xoffset": "3",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "124",
        "@x": "51",
        "@y": "315",
        "@width": "14",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "24",
        "@page": "0",
        "@chnl": "15"
      },
      {
        "@id": "125",
        "@x": "324",
        "@y": "51",
        "@width": "28",
        "@height": "50",
        "@xoffset": "-1",
        "@yoffset": "17",
        "@xadvance": "42",
        "@page": "0",
        "@chnl": "15"
      }
    ]
  }
}

const a_out = []
for (const s of font.chars.char) {
    a_out.push( {
        id: parseInt(s["@id"]),
        x: parseFloat(s["@x"]),
        y: parseFloat(s["@y"]),
        w: parseFloat(s["@width"]),
        h: parseFloat(s["@height"]),
        xoff: parseFloat(s["@xoffset"]),
        yoff: parseFloat(s["@yoffset"]),
        xadv: parseFloat(s["@xadvance"])
    });
}

console.log(JSON.stringify(a_out, null, 4))